/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameStatus = IDL.Variant({
  'completed' : IDL.Null,
  'locked' : IDL.Null,
  'unlocked' : IDL.Null,
});
export const GameProgress = IDL.Record({
  'status' : GameStatus,
  'voteCount' : IDL.Nat,
  'gameId' : IDL.Nat,
  'incorrectVotes' : IDL.Nat,
  'correctVotes' : IDL.Nat,
  'coinsEarned' : IDL.Nat,
});
export const UserState = IDL.Record({
  'gameStates' : IDL.Vec(GameProgress),
  'wallet' : IDL.Nat,
});
export const VoteResult = IDL.Record({
  'coins' : IDL.Nat,
  'isMatch' : IDL.Bool,
});

export const idlService = IDL.Service({
  'completeGame' : IDL.Func([IDL.Nat], [], []),
  'getGameProgress' : IDL.Func([IDL.Nat], [GameProgress], ['query']),
  'getUserState' : IDL.Func([], [UserState], ['query']),
  'getWallet' : IDL.Func([], [IDL.Nat], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([], [], []),
  'resetGame' : IDL.Func([IDL.Nat], [], []),
  'unlockGame' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'updateGameStatus' : IDL.Func([IDL.Nat, GameStatus], [], []),
  'vote' : IDL.Func([IDL.Nat, IDL.Bool], [VoteResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameStatus = IDL.Variant({
    'completed' : IDL.Null,
    'locked' : IDL.Null,
    'unlocked' : IDL.Null,
  });
  const GameProgress = IDL.Record({
    'status' : GameStatus,
    'voteCount' : IDL.Nat,
    'gameId' : IDL.Nat,
    'incorrectVotes' : IDL.Nat,
    'correctVotes' : IDL.Nat,
    'coinsEarned' : IDL.Nat,
  });
  const UserState = IDL.Record({
    'gameStates' : IDL.Vec(GameProgress),
    'wallet' : IDL.Nat,
  });
  const VoteResult = IDL.Record({ 'coins' : IDL.Nat, 'isMatch' : IDL.Bool });
  
  return IDL.Service({
    'completeGame' : IDL.Func([IDL.Nat], [], []),
    'getGameProgress' : IDL.Func([IDL.Nat], [GameProgress], ['query']),
    'getUserState' : IDL.Func([], [UserState], ['query']),
    'getWallet' : IDL.Func([], [IDL.Nat], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([], [], []),
    'resetGame' : IDL.Func([IDL.Nat], [], []),
    'unlockGame' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'updateGameStatus' : IDL.Func([IDL.Nat, GameStatus], [], []),
    'vote' : IDL.Func([IDL.Nat, IDL.Bool], [VoteResult], []),
  });
};

export const init = ({ IDL }) => { return []; };