/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameProgress {
  'status' : GameStatus,
  'voteCount' : bigint,
  'gameId' : bigint,
  'incorrectVotes' : bigint,
  'correctVotes' : bigint,
  'coinsEarned' : bigint,
}
export type GameStatus = { 'completed' : null } |
  { 'locked' : null } |
  { 'unlocked' : null };
export interface UserState {
  'gameStates' : Array<GameProgress>,
  'wallet' : bigint,
}
export interface VoteResult { 'coins' : bigint, 'isMatch' : boolean }
export interface _SERVICE {
  'completeGame' : ActorMethod<[bigint], undefined>,
  'getGameProgress' : ActorMethod<[bigint], GameProgress>,
  'getUserState' : ActorMethod<[], UserState>,
  'getWallet' : ActorMethod<[], bigint>,
  'isRegistered' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[], undefined>,
  'resetGame' : ActorMethod<[bigint], undefined>,
  'unlockGame' : ActorMethod<[bigint], string>,
  'updateGameStatus' : ActorMethod<[bigint, GameStatus], undefined>,
  'vote' : ActorMethod<[bigint, boolean], VoteResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];