/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserState {
    gameStates: Array<GameProgress>;
    wallet: bigint;
}
export interface GameProgress {
    status: GameStatus;
    voteCount: bigint;
    gameId: bigint;
    incorrectVotes: bigint;
    correctVotes: bigint;
    coinsEarned: bigint;
}
export interface VoteResult {
    coins: bigint;
    isMatch: boolean;
}
export enum GameStatus {
    completed = "completed",
    locked = "locked",
    unlocked = "unlocked"
}
export interface backendInterface {
    completeGame(gameId: bigint): Promise<void>;
    getGameProgress(gameId: bigint): Promise<GameProgress>;
    getUserState(): Promise<UserState>;
    getWallet(): Promise<bigint>;
    isRegistered(): Promise<boolean>;
    register(): Promise<void>;
    resetGame(gameId: bigint): Promise<void>;
    unlockGame(gameId: bigint): Promise<string>;
    updateGameStatus(gameId: bigint, status: GameStatus): Promise<void>;
    vote(gameId: bigint, isMatch: boolean): Promise<VoteResult>;
}
import type { GameProgress as _GameProgress, GameStatus as _GameStatus, UserState as _UserState } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeGame(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeGame(arg0);
            return result;
        }
    }
    async getGameProgress(arg0: bigint): Promise<GameProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameProgress(arg0);
                return from_candid_GameProgress_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameProgress(arg0);
            return from_candid_GameProgress_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserState(): Promise<UserState> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserState();
                return from_candid_UserState_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserState();
            return from_candid_UserState_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWallet(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallet();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallet();
            return result;
        }
    }
    async isRegistered(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isRegistered();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRegistered();
            return result;
        }
    }
    async register(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register();
            return result;
        }
    }
    async resetGame(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetGame(arg0);
            return result;
        }
    }
    async unlockGame(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockGame(arg0);
            return result;
        }
    }
    async updateGameStatus(arg0: bigint, arg1: GameStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGameStatus(arg0, to_candid_GameStatus_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGameStatus(arg0, to_candid_GameStatus_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async vote(arg0: bigint, arg1: boolean): Promise<VoteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.vote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.vote(arg0, arg1);
            return result;
        }
    }
}
function from_candid_GameProgress_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameProgress): GameProgress {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_GameStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameStatus): GameStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserState_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserState): UserState {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _GameStatus;
    voteCount: bigint;
    gameId: bigint;
    incorrectVotes: bigint;
    correctVotes: bigint;
    coinsEarned: bigint;
}): {
    status: GameStatus;
    voteCount: bigint;
    gameId: bigint;
    incorrectVotes: bigint;
    correctVotes: bigint;
    coinsEarned: bigint;
} {
    return {
        status: from_candid_GameStatus_n3(_uploadFile, _downloadFile, value.status),
        voteCount: value.voteCount,
        gameId: value.gameId,
        incorrectVotes: value.incorrectVotes,
        correctVotes: value.correctVotes,
        coinsEarned: value.coinsEarned
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gameStates: Array<_GameProgress>;
    wallet: bigint;
}): {
    gameStates: Array<GameProgress>;
    wallet: bigint;
} {
    return {
        gameStates: from_candid_vec_n7(_uploadFile, _downloadFile, value.gameStates),
        wallet: value.wallet
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    locked: null;
} | {
    unlocked: null;
}): GameStatus {
    return "completed" in value ? GameStatus.completed : "locked" in value ? GameStatus.locked : "unlocked" in value ? GameStatus.unlocked : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameProgress>): Array<GameProgress> {
    return value.map((x)=>from_candid_GameProgress_n1(_uploadFile, _downloadFile, x));
}
function to_candid_GameStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameStatus): _GameStatus {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameStatus): {
    completed: null;
} | {
    locked: null;
} | {
    unlocked: null;
} {
    return value == GameStatus.completed ? {
        completed: null
    } : value == GameStatus.locked ? {
        locked: null
    } : value == GameStatus.unlocked ? {
        unlocked: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
